// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZWVkmlR-jQd6iKYNTjkoOQlbo5Gf3jY',
    appId: '1:209388780377:web:079366b7f2f98abc85aa48',
    messagingSenderId: '209388780377',
    projectId: 'tasks-managment-15bb4',
    authDomain: 'tasks-managment-15bb4.firebaseapp.com',
    storageBucket: 'tasks-managment-15bb4.appspot.com',
    measurementId: 'G-BQPXK1CYXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-L5LJOiUk3emtCjSG2Ds2FuCwSlhRAk',
    appId: '1:209388780377:android:c921d8d30dd3261685aa48',
    messagingSenderId: '209388780377',
    projectId: 'tasks-managment-15bb4',
    storageBucket: 'tasks-managment-15bb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ovI1c5ltgjsX1c0nimKNhF1rVhPbEKw',
    appId: '1:209388780377:ios:505c58ded7e7bcdc85aa48',
    messagingSenderId: '209388780377',
    projectId: 'tasks-managment-15bb4',
    storageBucket: 'tasks-managment-15bb4.appspot.com',
    iosClientId:
        '209388780377-541p0vmclek6vt3d8r8djirjlousiblc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ovI1c5ltgjsX1c0nimKNhF1rVhPbEKw',
    appId: '1:209388780377:ios:07ad0f7b369682e385aa48',
    messagingSenderId: '209388780377',
    projectId: 'tasks-managment-15bb4',
    storageBucket: 'tasks-managment-15bb4.appspot.com',
    iosClientId:
        '209388780377-77vlbsh39ipbmdm72kgqu8a6svmiseob.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksManagement.RunnerTests',
  );
}
